[package]
name = "sorcat-eval"
version = "0.1.0"
edition = "2024"

[dependencies]
indexmap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
syn = { version = "2.0", features = ["full", "parsing", "visit"] }
thiserror = { workspace = true }

[dev-dependencies]
sorcat-core = { path = "../sorcat-core" }
